### ISSUE TITLE
Event transformations for higher level events

### ISSUE THREAD

**Issue by lucidd** [PistonDevelopers/input#32]
# Idea

The basic idea is to have some kind of stream of input events that can be transformed. With that it would be possible to transfrom a stream of raw low level events like button pressed or mouse moved to higher level events like double click or mouse dragged.

Transformations should be able to:

- Emit new events
- Omit old Events
- Passthrough old Events

# Use cases

- Key Sequences (Konami Code)
- Key Combination (Ctrl-C) 
- Drag Event
- Double Click / Tap Events
- Touch / Mouse Gesture Events

It could also potentaly used to solve #11 

You could also go as far as implementing an application specific transformation that transforms
raw or higher level events to application specific events like Move or Attack.

raw touch events => swipe gesture event => Attack Event

# Implementation

I don't think it is possible to implement something like that with the current design since you cant extend
the Events. I think #30 with the `Event` trait should help with this.

# Open Questions

- Interaction with the Gameloop
- Interaction with the Backend (SDL2)

# References

- Dart Event Streams [onKeyPress](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html.Document#id_onKeyPress)
- Dart [StreamTransfromer](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-async.StreamTransformer)
- Spec for [Reactive Streams](https://github.com/reactive-streams/reactive-streams)

**Comment by bvssvni** [comment]
It is possible to use [ai_behavior](https://github.com/pistondevelopers/ai_behavior) to something like this.

Any this is outside the scope of this library, so I'll close this.
